packages:
  - memorysmith-frontend
  - memorysmith-backend
  - memorysmith-backend/packages/*
  - memorysmith-backend/services/*
  - memorysmith-backend/apps/*
  - memorysmith-infra

allowBuilds:
  esbuild: true
